# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google3.net.proto2.python.public import descriptor
from google3.net.proto2.python.public import message
from google3.net.proto2.python.public import reflection
from google3.net.proto2.proto import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='quality/trustrank/frontend/externaltest/external_test.proto',
  package='',
  serialized_pb='\n;quality/trustrank/frontend/externaltest/external_test.proto\"\'\n\x08\x43GIParam\x12\x0c\n\x04Name\x18\x01 \x02(\x0c\x12\r\n\x05Value\x18\x02 \x02(\x0c\"g\n\x0bRequestData\x12\x13\n\x0bRequestPath\x18\x01 \x02(\x0c\x12\x19\n\x06Params\x18\x02 \x03(\x0b\x32\t.CGIParam\x12\x10\n\x08PostData\x18\x03 \x01(\x0c\x12\x16\n\x0eServerResponse\x18\x04 \x02(\x0c\"M\n\x0bHashRequest\x12\x12\n\nHashPrefix\x18\x01 \x02(\x0c\x12\x16\n\x0eServerResponse\x18\x02 \x02(\x0c\x12\x12\n\nExpression\x18\x03 \x01(\x0c\"H\n\x08StepData\x12\x1e\n\x08Requests\x18\x01 \x03(\x0b\x32\x0c.RequestData\x12\x1c\n\x06Hashes\x18\x02 \x03(\x0b\x32\x0c.HashRequest\"7\n\x08TestData\x12\x18\n\x05Steps\x18\x01 \x03(\x0b\x32\t.StepData\x12\x11\n\tClientKey\x18\x02 \x02(\x0c')




_CGIPARAM = descriptor.Descriptor(
  name='CGIParam',
  full_name='CGIParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Name', full_name='CGIParam.Name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Value', full_name='CGIParam.Value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=102,
)


_REQUESTDATA = descriptor.Descriptor(
  name='RequestData',
  full_name='RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='RequestPath', full_name='RequestData.RequestPath', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Params', full_name='RequestData.Params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='PostData', full_name='RequestData.PostData', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ServerResponse', full_name='RequestData.ServerResponse', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=207,
)


_HASHREQUEST = descriptor.Descriptor(
  name='HashRequest',
  full_name='HashRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='HashPrefix', full_name='HashRequest.HashPrefix', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ServerResponse', full_name='HashRequest.ServerResponse', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Expression', full_name='HashRequest.Expression', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=209,
  serialized_end=286,
)


_STEPDATA = descriptor.Descriptor(
  name='StepData',
  full_name='StepData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Requests', full_name='StepData.Requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Hashes', full_name='StepData.Hashes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=288,
  serialized_end=360,
)


_TESTDATA = descriptor.Descriptor(
  name='TestData',
  full_name='TestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Steps', full_name='TestData.Steps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ClientKey', full_name='TestData.ClientKey', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=362,
  serialized_end=417,
)

_REQUESTDATA.fields_by_name['Params'].message_type = _CGIPARAM
_STEPDATA.fields_by_name['Requests'].message_type = _REQUESTDATA
_STEPDATA.fields_by_name['Hashes'].message_type = _HASHREQUEST
_TESTDATA.fields_by_name['Steps'].message_type = _STEPDATA
DESCRIPTOR.message_types_by_name['CGIParam'] = _CGIPARAM
DESCRIPTOR.message_types_by_name['RequestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['HashRequest'] = _HASHREQUEST
DESCRIPTOR.message_types_by_name['StepData'] = _STEPDATA
DESCRIPTOR.message_types_by_name['TestData'] = _TESTDATA

class CGIParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CGIPARAM
  
  # @@protoc_insertion_point(class_scope:CGIParam)

class RequestData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTDATA
  
  # @@protoc_insertion_point(class_scope:RequestData)

class HashRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HASHREQUEST
  
  # @@protoc_insertion_point(class_scope:HashRequest)

class StepData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STEPDATA
  
  # @@protoc_insertion_point(class_scope:StepData)

class TestData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTDATA
  
  # @@protoc_insertion_point(class_scope:TestData)

# @@protoc_insertion_point(module_scope)
